version: '3'

services:
  mysql57:
    build: $PWD/mysql5.7
    restart: always
    volumes:
      - $PWD/mysql5.7/mysql.conf.d/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - /srv/dockerData/mysql:/var/lib/mysql
    privileged: true
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306
    command:
      - --sql-mode=NO_ENGINE_SUBSTITUTION
  php71:
    build: $PWD/php7.1
    restart: always
    volumes:
      - /srv/web/www:/srv/web/www
      - $PWD/php7.1/php.ini:/usr/local/etc/php/php.ini
      - /srv/dockerCache/composer:/composer
    privileged: true
    links:
      - mysql57
      - redis4
    depends_on:
      - mysql57
  web:
    build: $PWD/nginx
    restart: always
    volumes:
      - /srv/web/www:/srv/web/www
      - $PWD/nginx/conf.d:/etc/nginx/conf.d
      - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf
    privileged: true
    ports:
      - 80:80
    links:
      - php71
    depends_on:
      - php71
  redis4:
    image: 'redis:4.0'
    restart: always
    command:
      - --appendonly yes
    volumes:
      - /srv/dockerData/redis:/data
    privileged: true
    ports:
      - 6379:6379
