version: '3'

services:
#  mysql56:
#    container_name: mysql56
#    build: $PWD/mysql5.6
#    restart: always
#    volumes:
#      - /srv/dockerData/mysql56:/var/lib/mysql
#    privileged: true
#    environment:
#      MYSQL_ROOT_PASSWORD: 123456
#    ports:
#      - 3307:3306
#    command:
#      - --sql-mode=NO_ENGINE_SUBSTITUTION
#    networks:
#      app_net:
#        ipv4_address: 172.16.238.2


  mysql57:
    container_name: mysql57
    build: $PWD/mysql5.7
    restart: always
    volumes:
      - $PWD/mysql5.7/mysql.conf.d/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - /srv/dockerData/mysql:/var/lib/mysql
    privileged: true
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306
    command:
      - --sql-mode=NO_ENGINE_SUBSTITUTION
#      - --general-log=ON
#      - --general-log-file=/srv/web/logs/mysql.log
    networks:
      app_net:
        ipv4_address: 172.16.238.3

  mysql8:
    container_name: mysql8
    build: $PWD/mysql8
    restart: always
    volumes:
      - /srv/dockerData/mysql8:/var/lib/mysql
    privileged: true
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3308:3306
    command:
      - --default-authentication-plugin=mysql_native_password
    #  - --sql-mode=NO_ENGINE_SUBSTITUTION
    #      - --general-log=ON
    #      - --general-log-file=/srv/web/logs/mysql.log
    networks:
      app_net:
        ipv4_address: 172.16.238.14

#  php56:
#    container_name: php56
#    build: $PWD/php5.6
#    restart: always
#    volumes:
#      - /srv/web/www:/srv/web/www
#      - /srv/web/logs:/srv/web/logs
#      - $PWD/php5.6/php.ini:/usr/local/etc/php/php.ini
#      - composer-data56:/composer56
#    privileged: true
#    working_dir: /srv/web/www
#    links:
#      - mysql56
#      - mysql57
#      - redis4
#    depends_on:
#      - mysql56
#      - mysql57
#      - redis4
#    networks:
#      app_net:
#        ipv4_address: 172.16.238.5


  php71:
    container_name: php71
    build: $PWD/php7.1
    restart: always
    volumes:
      - /srv/web/www:/srv/web/www
      - /srv/web/logs:/srv/web/logs
      - $PWD/php7.1/php.ini:/usr/local/etc/php/php.ini
      - composer-data71:/composer71
    privileged: true
    working_dir: /srv/web/www
    ports:
      - '9501-9510:9501-9510'
    links:
#      - mysql56
      - mysql57
      - redis4
    depends_on:
#      - mysql56
      - mysql57
      - redis4
    networks:
      app_net:
        ipv4_address: 172.16.238.6


  php72:
    container_name: php72
    build: $PWD/php7.2
    restart: always
    volumes:
      - /srv/web/www:/srv/web/www
      - /srv/web/logs:/srv/web/logs
      - $PWD/php7.2/php.ini:/usr/local/etc/php/php.ini
      - composer-data72:/composer72
    privileged: true
    working_dir: /srv/web/www
    ports:
      - '9511-9521:9501-9511'
    links:
#      - mysql56
      - mysql57
      - redis4
    depends_on:
#      - mysql56
      - mysql57
      - redis4
    networks:
      app_net:
        ipv4_address: 172.16.238.7

  php73:
    container_name: php73
    build: $PWD/php7.3
    restart: always
    volumes:
      - /srv/web/www:/srv/web/www
      - /srv/web/logs:/srv/web/logs
      - $PWD/php7.3/php.ini:/usr/local/etc/php/php.ini
      - composer-data73:/composer73
    privileged: true
    working_dir: /srv/web/www
    ports:
      - '9511-9521:9501-9511'
    links:
      #      - mysql56
      - mysql8
      - redis4
    depends_on:
      #      - mysql56
      - mysql8
      - redis4
    networks:
      app_net:
        ipv4_address: 172.16.238.13


  nginx:
    container_name: nginx
    build: $PWD/nginx
    restart: always
    volumes:
      - /srv/web/www:/srv/web/www
      - $PWD/nginx/conf.d:/etc/nginx/conf.d
      - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf
    privileged: true
    ports:
      - 80:80
    links:
#      - php56
      - php71
      - php72
    depends_on:
#      - php56
      - php71
      - php72
    networks:
      app_net:
        ipv4_address: 172.16.238.8


  redis4:
    container_name: redis4
    build: $PWD/redis4.0
    restart: always
    command:
      - --appendonly yes
    volumes:
      - /srv/dockerData/redis:/data
    privileged: true
    ports:
      - 6379:6379
    networks:
      app_net:
        ipv4_address: 172.16.238.9

  mongo:
    container_name: mongo3.4
    image: mongo:3.4
    restart: always
    volumes:
      - /srv/dockerData/mongodbData:/data/db
    privileged: true
    ports:
      - '27017:27017'
    #    environment:
    #      MONGO_INITDB_ROOT_USERNAME: root
    #      MONGO_INITDB_ROOT_PASSWORD: 123456
    networks:
      app_net:
        ipv4_address: 172.16.238.10

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    privileged: true
    #    environment:
    #      ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
    networks:
      app_net:
        ipv4_address: 172.16.238.11

  portainer:
    container_name: portainer
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    privileged: true
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      app_net:
        ipv4_address: 172.16.238.12

# 挂载
volumes:
  composer-data73:
    external: true
  composer-data56:
    external: true
  composer-data71:
    external: true
  composer-data72:
    external: true
  portainer_data:
    external: true

networks:
  app_net:
    external: true

# 网络配置
#networks:
#  lnmp_net:
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.16.238.0/24
